### ISSUE TITLE
Adding a phpunit helper/trait

### ISSUE THREAD

**Issue by ohnotnow** [orkhanahmadov/laravel-zip-validator#1]
Hi,

Thanks for this package - I'm already getting a lot of use out of it - much appreciated.

I wonder if you'd be open to adding a phpunit/response helper to this which people could use in their tests?  I was going to do it myself, but thought it might be nice to have in the same project.  We have a few apps that let users download Zip's of 'stuff' and testing it is a bit hacky.  So if we could re-use a part of this to allow something like :

```php
$response = $this->get(....);

$response->assertZipContains('images.zip', ['images/1.jpg', 'images/2.jpg']);
```

If you don't think that belongs here I'll happily write my own package though :-)

**Comment by orkhanahmadov** [comment]
Hey,

Happy that it helps you too.

That would be interesting feature I have to say. But not fully sure how we can implement it in current state of package. We only have `ZipContent` class which is just Laravel Rule object. If we want to use it somewhere else we need to consider few things: 
* `$attribute` parameter of [`passes()`](https://github.com/orkhanahmadov/laravel-zip-validator/blob/master/src/Rules/ZipContent.php#L50) method will become redundant;
* [`readContent()`](https://github.com/orkhanahmadov/laravel-zip-validator/blob/master/src/Rules/ZipContent.php#L130) method accepts `Illuminate\Http\UploadedFile` instance of file as parameter, downloadable file won't be same instance.

That being said, I like your offer reusing it in different places, not just when validating uploads. But for that, first we need to extract main zip validator logic from `ZipContent` to a dedicated, more generic class, then we can use it inside validator rule and phpunit/response helper.

**Comment by ohnotnow** [comment]
(Sorry for the slow reply to my own issue! Came down with the cold so I am not very 'on the ball').

Yeah - I had a look through the code before I posted and saw that the readContent() to an UploadedFile.  Then I went off to try and figure out if there was anything added recently in the way of testing a file download in the frameworks TestResponse and saw there still isn't anything and began to work on a PR for it (things like `$response->assertAttachment('myfile.zip`).  Then I got the cold and my brain stopped working... ;-)

Once I've shaken this off I might carry on working on the PR for the framework that would in turn make re-using some of the code here easier.  Thanks for taking the time to answer thoughtfully! :-)

**Comment by orkhanahmadov** [comment]
Hi @ohnotnow 

I just tagged [1.5.0](https://github.com/orkhanahmadov/laravel-zip-validator/releases/tag/1.5.0) version. In this release, I extracted validator logic outside of validation rule, to its dedicated class.

Now you are free to use ZIP validation for other purposes, checking ZIP content of downloaded files, for example.

``` php
use Orkhanahmadov\ZipValidator\Validator;

$failedFiles = Validator::rules(['document.pdf', 'song.mp3'])->validate('absolute/path/to/zip/file.zip');
$this->assertCount(0, $failedFiles); // success
```

Take a look at [`rules()`](https://github.com/orkhanahmadov/laravel-zip-validator/blob/master/src/Validator.php#L41) and [`validate()`](https://github.com/orkhanahmadov/laravel-zip-validator/blob/master/src/Validator.php#L53) methods on Validator class.

You can extend Laravel's test response helper with something like `assertZipContains()` and wrap Validator logic inside.
