### ISSUE TITLE
Errors messages in laravel 8

### ISSUE THREAD

**Issue by shelderr** [orkhanahmadov/laravel-zip-validator#3]
Validator message cant find translation file. Error looks like this "zipvalidator::messagesfailed"
`https://github.com/orkhanahmadov/laravel-zip-validator/blob/master/src/Rules/ZipContent.php`

**Comment by crslp** [comment]
Just stumbled upon this.
The language-folder is missing. The directory structure should look like this:
`vendor/orkhanahmadov/laravel-zip-validator/resources/lang/en/messages.php`
(note the "en"-directory which is not present in current release).

**Comment by orkhanahmadov** [comment]
Thanks for reporting this bug. I pushed a fix and tagged a new version [1.7.1](https://github.com/orkhanahmadov/laravel-zip-validator/releases/tag/1.7.1)
